# Generated by Django 5.2 on 2025-04-17 08:42

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(blank=True, help_text='Suffix like Jr, Sr, II, or custom (optional)', max_length=20, null=True)),
                ('company_id', models.CharField(help_text='Format: MA0001 to MA9999', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Company ID must be in the format MA0001 to MA9999', regex='^MA[0-9]{4}$')])),
                ('department', models.CharField(choices=[('IT Department', 'IT Department'), ('Asset Management', 'Asset Management'), ('Document Control', 'Document Control'), ('Finance & Budgeting', 'Finance & Budgeting'), ('Operations', 'Operations'), ('Facilities & Maintenance', 'Facilities & Maintenance'), ('Human Resources', 'Human Resources'), ('Administration', 'Administration')], help_text='Select a department from the predefined list.', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(help_text='Required. Upload a 1x1 photo (JPG or PNG), max 2MB, white background', upload_to='employees/', validators=[core.models.validate_image_size, core.models.validate_image_extension])),
                ('email', models.EmailField(help_text='Only Gmail addresses are allowed', max_length=254, unique=True, validators=[core.models.validate_gmail_email])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('department__in', ['IT Department', 'Asset Management', 'Document Control', 'Finance & Budgeting', 'Operations', 'Facilities & Maintenance', 'Human Resources', 'Administration'])), name='valid_department_constraint'),
        ),
    ]
