# Generated by Django 5.2 on 2025-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationrecipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationRecipient',
        ),
        migrations.AddField(
            model_name='employee',
            name='notified',
            field=models.BooleanField(default=False, help_text='Marks if approval email has been sent to this employee'),
        ),
    ]
