# Generated by Django 5.2 on 2025-04-24 04:32

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_notificationrecipient_employee_notified'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='valid_department_constraint',
        ),
        migrations.AddField(
            model_name='employee',
            name='userrole',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Ticket Agent', 'Ticket Agent'), ('System Admin', 'System Admin')], default='Employee', help_text='Defines the role of the user', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_id',
            field=models.CharField(help_text='Format: MA0001 to MA9999', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Company ID format is invalid. Please enter a number like 0001', regex='^MA[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, help_text='Optional. Must be Jr, Sr, or Roman numeral suffix like III–X', max_length=20, null=True, validators=[core.models.validate_roman_suffix]),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('userrole__in', ['Employee', 'Ticket Agent', 'System Admin'])), name='valid_userrole_constraint'),
        ),
    ]
