export const users = [
  // Active (5)
  {
    id: 'U001',
    companyId: 'IT0001',
    lastName: 'San Jose',
    firstName: 'Bonjing',
    middleName: 'Peralta',
    suffix: 'Jr.',
    department: 'Budget Department', // from Finance Department
    role: 'User',
    status: 'Active',
    dateCreated: '2025-05-23',
  },
  {
    id: 'U002',
    companyId: 'IT0002',
    lastName: 'Garcia',
    firstName: 'Leonard',
    middleName: 'B.',
    suffix: '',
    department: 'IT Department', // from Technical Support mapped to IT Department
    role: 'Ticket Agent',
    status: 'Active',
    dateCreated: '2025-02-20',
  },
  {
    id: 'U003',
    companyId: 'IT0003',
    lastName: 'Cruz',
    firstName: 'Daniel',
    middleName: 'Lopez',
    suffix: '',
    department: 'IT Department',
    role: 'System Admin',
    status: 'Active',
    dateCreated: '2025-03-10',
  },
  {
    id: 'U004',
    companyId: 'IT0004',
    lastName: 'Navarro',
    firstName: 'Alyssa',
    middleName: 'Reyes',
    suffix: '',
    department: 'Asset Department', // from Human Resources mapped to Asset Department
    role: 'User',
    status: 'Active',
    dateCreated: '2025-04-05',
  },
  {
    id: 'U005',
    companyId: 'IT0005',
    lastName: 'Santos',
    firstName: 'Marco',
    middleName: 'Antonio',
    suffix: '',
    department: 'Asset Department', // from Operations mapped to Asset Department
    role: 'Ticket Agent',
    status: 'Active',
    dateCreated: '2025-01-28',
  },

  // Inactive (5)
  {
    id: 'U006',
    companyId: 'IT0006',
    lastName: 'Dela Cruz',
    firstName: 'Anna',
    middleName: 'Marie',
    suffix: '',
    department: 'Asset Department', // from Operations mapped to Asset Department
    role: 'User',
    status: 'Inactive',
    dateCreated: '2025-05-01',
  },
  {
    id: 'U007',
    companyId: 'IT0007',
    lastName: 'Villanueva',
    firstName: 'Catherine',
    middleName: 'Santos',
    suffix: '',
    department: 'IT Department',
    role: 'System Admin',
    status: 'Inactive',
    dateCreated: '2025-01-15',
  },
  {
    id: 'U008',
    companyId: 'IT0008',
    lastName: 'Tan',
    firstName: 'Joshua',
    middleName: '',
    suffix: '',
    department: 'Budget Department', // from Finance Department
    role: 'User',
    status: 'Inactive',
    dateCreated: '2025-02-09',
  },
  {
    id: 'U009',
    companyId: 'IT0009',
    lastName: 'Lim',
    firstName: 'Grace',
    middleName: 'Yu',
    suffix: '',
    department: 'Asset Department', // from Customer Service mapped to Asset Department
    role: 'Ticket Agent',
    status: 'Inactive',
    dateCreated: '2025-03-12',
  },
  {
    id: 'U010',
    companyId: 'IT0010',
    lastName: 'Morales',
    firstName: 'Ricky',
    middleName: 'G.',
    suffix: '',
    department: 'Asset Department', // from Human Resources mapped to Asset Department
    role: 'System Admin',
    status: 'Inactive',
    dateCreated: '2025-04-15',
  },

  // Pending (5)
  {
    id: 'U011',
    companyId: 'IT0011',
    lastName: 'Reyes',
    firstName: 'Maricel',
    middleName: 'Gomez',
    suffix: '',
    department: 'Asset Department', // from Human Resources mapped to Asset Department
    role: 'Ticket Agent',
    status: 'Pending',
    dateCreated: '2025-04-18',
  },
  {
    id: 'U012',
    companyId: 'IT0012',
    lastName: 'Tan',
    firstName: 'Michael',
    middleName: '',
    suffix: '',
    department: 'Asset Department', // from Customer Service mapped to Asset Department
    role: 'User',
    status: 'Pending',
    dateCreated: '2025-05-20',
  },
  {
    id: 'U013',
    companyId: 'IT0013',
    lastName: 'Ocampo',
    firstName: 'Bianca',
    middleName: 'Cruz',
    suffix: '',
    department: 'IT Department', // from Technical Support mapped to IT Department
    role: 'System Admin',
    status: 'Pending',
    dateCreated: '2025-03-30',
  },
  {
    id: 'U014',
    companyId: 'IT0014',
    lastName: 'Ramos',
    firstName: 'Luis',
    middleName: '',
    suffix: '',
    department: 'Asset Department', // from Operations mapped to Asset Department
    role: 'User',
    status: 'Pending',
    dateCreated: '2025-02-02',
  },
  {
    id: 'U015',
    companyId: 'IT0015',
    lastName: 'Torres',
    firstName: 'Jenny',
    middleName: 'Ann',
    suffix: '',
    department: 'Budget Department', // from Finance Department
    role: 'Ticket Agent',
    status: 'Pending',
    dateCreated: '2025-05-21',
  },
];
