const USER_STORAGE_KEY = 'users';

export const users = [
  // Active (5)
  {
    id: 'U001',
    companyId: 'IT0001',
    lastName: 'San Jose',
    firstName: 'Bonjing',
    middleName: 'Peralta',
    suffix: 'Jr.',
    department: 'Budget Department',
    role: 'User',
    status: 'Active',
    dateCreated: '2025-05-23',
    email: 'bonjing.sanjose@company.com',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U002',
    companyId: 'IT0002',
    lastName: 'Garcia',
    firstName: 'Leonard',
    middleName: 'B.',
    suffix: '',
    department: 'IT Department',
    role: 'Ticket Coordinator',
    status: 'Active',
    dateCreated: '2025-02-20',
    email: 'leonard.garcia@company.com',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U003',
    companyId: 'IT0003',
    lastName: 'Cruz',
    firstName: 'Daniel',
    middleName: 'Lopez',
    suffix: '',
    department: 'IT Department',
    role: 'System Admin',
    status: 'Active',
    dateCreated: '2025-03-10',
    email: 'daniel.cruz@company.com',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U004',
    companyId: 'IT0004',
    lastName: 'Navarro',
    firstName: 'Alyssa',
    middleName: 'Reyes',
    suffix: '',
    department: 'Asset Department',
    role: 'User',
    status: 'Active',
    dateCreated: '2025-04-05',
    email: 'alyssa.navarro@company.com',
    profileImage: 'https://images.unsplash.com/photo-1494790108755-2616b332e234?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U005',
    companyId: 'IT0005',
    lastName: 'Santos',
    firstName: 'Marco',
    middleName: 'Antonio',
    suffix: '',
    department: 'Asset Department',
    role: 'Ticket Coordinator',
    status: 'Active',
    dateCreated: '2025-01-28',
    email: 'marco.santos@company.com',
    profileImage: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face',
  },

  // Inactive (5)
  {
    id: 'U006',
    companyId: 'IT0006',
    lastName: 'Dela Cruz',
    firstName: 'Anna',
    middleName: 'Marie',
    suffix: '',
    department: 'Asset Department',
    role: 'User',
    status: 'Inactive',
    dateCreated: '2025-05-01',
    email: 'anna.delacruz@company.com',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U007',
    companyId: 'IT0007',
    lastName: 'Villanueva',
    firstName: 'Catherine',
    middleName: 'Santos',
    suffix: '',
    department: 'IT Department',
    role: 'System Admin',
    status: 'Inactive',
    dateCreated: '2025-01-15',
    email: 'catherine.villanueva@company.com',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U008',
    companyId: 'IT0008',
    lastName: 'Tan',
    firstName: 'Joshua',
    middleName: '',
    suffix: '',
    department: 'Budget Department',
    role: 'User',
    status: 'Inactive',
    dateCreated: '2025-02-09',
    email: 'joshua.tan@company.com',
    profileImage: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U009',
    companyId: 'IT0009',
    lastName: 'Lim',
    firstName: 'Grace',
    middleName: 'Yu',
    suffix: '',
    department: 'Asset Department',
    role: 'Ticket Coordinator',
    status: 'Inactive',
    dateCreated: '2025-03-12',
    email: 'grace.lim@company.com',
    profileImage: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U010',
    companyId: 'IT0010',
    lastName: 'Morales',
    firstName: 'Ricky',
    middleName: 'G.',
    suffix: '',
    department: 'Asset Department',
    role: 'System Admin',
    status: 'Inactive',
    dateCreated: '2025-04-15',
    email: 'ricky.morales@company.com',
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
  },

  // Pending (5)
  {
    id: 'U011',
    companyId: 'IT0011',
    lastName: 'Reyes',
    firstName: 'Maricel',
    middleName: 'Gomez',
    suffix: '',
    department: 'Asset Department',
    role: 'Ticket Coordinator',
    status: 'Pending',
    dateCreated: '2025-04-18',
    email: 'maricel.reyes@company.com',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U012',
    companyId: 'IT0012',
    lastName: 'Tan',
    firstName: 'Michael',
    middleName: '',
    suffix: '',
    department: 'Asset Department',
    role: 'User',
    status: 'Pending',
    dateCreated: '2025-05-20',
    email: 'michael.tan@company.com',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U013',
    companyId: 'IT0013',
    lastName: 'Ocampo',
    firstName: 'Bianca',
    middleName: 'Cruz',
    suffix: '',
    department: 'IT Department',
    role: 'System Admin',
    status: 'Pending',
    dateCreated: '2025-03-30',
    email: 'bianca.ocampo@company.com',
    profileImage: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U014',
    companyId: 'IT0014',
    lastName: 'Ramos',
    firstName: 'Luis',
    middleName: '',
    suffix: '',
    department: 'Asset Department',
    role: 'User',
    status: 'Pending',
    dateCreated: '2025-02-02',
    email: 'luis.ramos@company.com',
    profileImage: 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 'U015',
    companyId: 'IT0015',
    lastName: 'Torres',
    firstName: 'Jenny',
    middleName: 'Ann',
    suffix: '',
    department: 'Budget Department',
    role: 'Ticket Coordinator',
    status: 'Pending',
    dateCreated: '2025-05-21',
    email: 'jenny.torres@company.com',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
  },
];

export const getUsers = () => {
  const data = localStorage.getItem(USER_STORAGE_KEY);
  return data ? JSON.parse(data) : [];
};

export const saveUsers = (users) => {
  localStorage.setItem(USER_STORAGE_KEY, JSON.stringify(users));
};

export const getUserById = (userId) => {
  const users = getUsers();
  return users.find(user => user.id === userId) || null;
};

// Initialize mock data only if empty
if (!localStorage.getItem(USER_STORAGE_KEY)) {
  saveUsers(users);
}

// Remove below lines after initial data load confirmed
// localStorage.removeItem(USER_STORAGE_KEY);
// saveUsers(users);