# Generated by Django 5.2.1 on 2025-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_ticket_number_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('On Process', 'On Process'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
