# Generated by Django 5.2.1 on 2025-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_category_alter_ticket_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
