# Generated by Django 5.2.1 on 2025-06-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticketcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
    ]
