# Generated by Django 5.2.1 on 2025-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='employee_images/default-profile.png', null=True, upload_to='employee_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Ticket Coordinator', 'Ticket Coordinator'), ('System Admin', 'System Admin')], default='Employee', max_length=20),
        ),
    ]
