# Generated by Django 5.2.1 on 2025-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_image_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
