# Generated by Django 5.2.1 on 2025-06-19 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
