# Generated by Django 5.2.1 on 2025-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
